package org.jboss.seam.test.integration.faces;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.InputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.container.test.api.OverProtocol;
import org.jboss.arquillian.container.test.api.RunAsClient;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.seam.test.integration.Country;
import org.jboss.seam.test.integration.Deployments;
import org.jboss.seam.ui.resource.WebResource;
import org.jboss.shrinkwrap.api.Archive;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.jbpm.taskmgmt.exe.TaskInstance;
import org.junit.Test;
import org.junit.runner.RunWith;

import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlPage;

/**
 * Regression tests for {@code s:convertDateTime}, {@code s:convertEnum}, and
 * {@code s:convertEntity}. These tags are generated by {@code seam-cdk-helper}
 * from {@code @FacesConverter} classes under {@code src/generated/jakarta/};
 * they are easy to miss because they are not RichFaces CDK components.
 */
@RunWith(Arquillian.class)
@RunAsClient
public class SeamUiConverterTagsTest
{
   private final WebClient client = new WebClient();

   public SeamUiConverterTagsTest()
   {
      client.setJavaScriptEnabled(false);
   }

   @ArquillianResource
   URL contextPath;

   @Deployment(name = "SeamUiConverterTagsTest")
   @OverProtocol("Servlet 5.0")
   public static Archive<?> createDeployment()
   {
      WebArchive war = Deployments.realSeamDeployment(SeamUiConverterTagsTest.class, SeamUiTagsBean.class);
      return war.addClasses(Country.class)
            .addAsLibrary(Deployments.jarFor(TaskInstance.class))
            .addAsWebResource("seam-ui-tags.xhtml", "seam-ui-tags.xhtml")
            .addAsWebResource("seam-ui-resource.xhtml", "seam-ui-resource.xhtml");
   }

   @Test
   public void seamUiTaglibDeclaresCdkHelperConverterTags() throws Exception
   {
      try (JarFile jar = new JarFile(Deployments.jarFor(WebResource.class)))
      {
         JarEntry entry = jar.getJarEntry("META-INF/s.taglib.xml");
         assertNotNull("Seam UI taglib missing from jboss-seam-ui-jakarta", entry);
         try (InputStream in = jar.getInputStream(entry))
         {
            String xml = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            assertTrue("convertDateTime missing from s.taglib.xml", xml.contains("<tag-name>convertDateTime</tag-name>"));
            assertTrue("convertEnum missing from s.taglib.xml", xml.contains("<tag-name>convertEnum</tag-name>"));
            assertTrue("convertEntity missing from s.taglib.xml", xml.contains("<tag-name>convertEntity</tag-name>"));
         }
      }
   }

   @Test
   public void convertDateTimeTagRendersFormattedTime() throws Exception
   {
      HtmlPage page = loadTagsPage();
      assertNotNull(page.getElementById("tag-convertDateTime"));
      assertTrue(page.getElementById("tag-convertDateTime").getTextContent().matches(".*\\d{2}:\\d{2}:\\d{2}.*"));
   }

   @Test
   public void convertEnumTagRendersEnumSelect() throws Exception
   {
      HtmlPage page = loadTagsPage();
      String html = page.asXml();
      assertTrue(html.contains("mainForm:tag-convertEnum"));
      assertTrue(html.contains("ACTIVE"));
      assertTrue(html.contains("PENDING"));
      assertTrue(html.contains("CLOSED"));
   }

   @Test
   public void convertEntityTagRendersEntitySelect() throws Exception
   {
      HtmlPage page = loadTagsPage();
      String html = page.asXml();
      assertTrue(html.contains("mainForm:tag-convertEntity"));
      assertTrue(html.contains("Seamland"));
   }

   private HtmlPage loadTagsPage() throws Exception
   {
      HtmlPage page = client.getPage(contextPath + "seam-ui-tags.seam");
      assertEquals("Seam UI Tags", page.getTitleText());
      return page;
   }
}
