<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.jboss</groupId>
		<artifactId>jboss-parent</artifactId>
		<version>10</version>
	</parent>
	<groupId>io.github.martinhickson</groupId>
	<artifactId>seam-cdk-helper</artifactId>
	<version>2.4.1-bravura-35</version>
	<packaging>maven-plugin</packaging>
	<name>Seam 2.3 CDK Helper for using RF 4 CDK</name>
	<url>http://seamframework.org</url>
	
	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
		<version.jandex.maven.plugin>3.5.3</version.jandex.maven.plugin>
		<version.jandex.index.format>10</version.jandex.index.format>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
			<version>2.0</version>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>3.1.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>8</source>
					<target>8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>io.smallrye</groupId>
				<artifactId>jandex-maven-plugin</artifactId>
				<version>${version.jandex.maven.plugin}</version>
				<executions>
					<execution>
						<id>make-index</id>
						<goals>
							<goal>jandex</goal>
						</goals>
						<configuration>
							<indexVersion>${version.jandex.index.format}</indexVersion>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
